name: Action 01

on: workflow_dispatch

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: CD to playwright
        run: cd playwright
    
      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Run Node app
        run: |
          cd node-app/
          npm install
          node server.js &

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
