name: Action 02

on: workflow_dispatch

jobs: 

  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Node app
        run: |
          cd node-app/
          npm install
          node server.js &

      - name: Sleep to allow application to start
        run: sleep 10s

      - name: Set up reverse proxy
        run: |
          echo "server {
              listen 3000;
              location / {
                  proxy_pass http://localhost:3001;
              }
          }" > default.conf
          docker run --rm -p 3001:3000 -v $(pwd)/default.conf:/etc/nginx/conf.d/default.conf nginx

      - name: Export application URL
        id: export-application-url
        run: |
          echo "APP_URL=http://localhost:3001" >> $GITHUB_ENV
          echo "::set-output name=app_url::http://localhost:3001"

  test:
    needs: run-app
    strategy:
      fail-fast: false
      matrix:
        browser: ['chromium', 'firefox', 'webkit']
    runs-on: ubuntu-latest

    env:
      APP_URL: ${{ needs.run-app.outputs.app_url }}

    steps:
      - name: git checkout repo
        run: |
          echo ${{ needs.run-app.outputs.app_url }}
          echo ${{ env.APP_URL }}

      - name: git checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          cd playwright
          npm install

      - name: Install Playwright Browsers
        run: |
          cd playwright
          npx playwright install --with-deps ${{ matrix.browser }}

      - name: Run Playwright tests
        run:  |
          cd playwright
          npx playwright test --project=${{ matrix.browser }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright/playwright-report/
          retention-days: 30

  merge:
    needs: [test]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd playwright
          npm install
       
      - uses: actions/download-artifact@v3
        with:
          path: playwright/playwright-report

      - name: Run Report Merge
        run:   |
          cd playwright
          pwd
          ls -l
          npm run merge

      - name: Display structure of Merged
        run: |
          cd playwright
          ls -R

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: html-report
          path: playwright/html-report/
          retention-days: 3

