name: Action 02

on: workflow_dispatch

jobs: 

  test:
    strategy:
      matrix:
        browser: ['chromium', 'firefox', 'webkit']
    runs-on: ubuntu-latest
    steps:
      - name: git checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
    
      - name: Install dependencies
        run: |
          cd playwright
          npm install

      - name: Install Playwright Browsers
        run: |
          cd playwright
          npx playwright install --with-deps ${{ matrix.browser }}

      - name: Run Node app
        run: |
          cd node-app/
          npm install
          node server.js &

      - name: Run Playwright tests
        run:  |
          cd playwright
          npx playwright test --project=${{ matrix.browser }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright/playwright-report/
          retention-days: 30

  merge:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd playwright
          npm install
       
      - uses: actions/download-artifact@v3
        with:
          path: playwright/playwright-report

      - name: Run Report Merge
        run:   |
          cd playwright
          pwd
          ls -l
          npm run merge

      - name: Display structure of Merged
        run: |
          cd playwright
          ls -R

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: html-report
          path: playwright/html-report/
          retention-days: 3

