name: Action 02

on: workflow_dispatch

jobs: 

  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Node app
        run: |
          cd react-shop-cart-main/
          npm install
          npm run build

      - name: View files
        run: ls -l

      - name: Save build files
        uses: actions/upload-artifact@master
        with:
          name: build-files
          path: react-shop-cart-main/build

  test:
    needs: build-app
    strategy:
      fail-fast: false
      matrix:
        browser: ['chromium', 'firefox', 'webkit']
    runs-on: ubuntu-latest

    env:
      APP_URL: ${{ needs.run-app.outputs.app_url }}

    steps:
      - name: curl to url
        run: curl https://hari-dom.loca.lt

      - name: git checkout repo
        run: |
          echo ${{ needs.run-app.outputs.app_url }}
          echo ${{ env.APP_URL }}

      - name: git checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - uses: actions/download-artifact@master
        with:
          name: build-files
          path: react-shop-cart-main/

      - name: Build Node app
        shell: bash
        run: |
          cd react-shop-cart-main/
          serve -s build &
      
      - name: Install dependencies
        run: |
          cd playwright
          npm install

      - name: Install Playwright Browsers
        run: |
          cd playwright
          npx playwright install --with-deps ${{ matrix.browser }}

      - name: Run Playwright tests
        run:  |
          cd playwright
          npx playwright test --project=${{ matrix.browser }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright/playwright-report/
          retention-days: 30

  merge:
    needs: [test]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd playwright
          npm install
       
      - uses: actions/download-artifact@v3
        with:
          path: playwright/playwright-report

      - name: Run Report Merge
        run:   |
          cd playwright
          pwd
          ls -l
          npm run merge

      - name: Display structure of Merged
        run: |
          cd playwright
          ls -R

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: html-report
          path: playwright/html-report/
          retention-days: 3

