name: Action 02

on: workflow_dispatch

jobs: 

  test:
    strategy:
      matrix:
        browser: ['chromium', 'firefox', 'webkit']
    runs-on: self-hosted
    steps:
      - name: git checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Node app
        run: |
          cd node-app/
          npm install
          forever start server.js

      - name: Run Playwright tests
        run:  |
          cd playwright
          npx playwright test --project=${{ matrix.browser }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
