name: Scheduled Playwright report cleanup 
on:
  schedule:
    - cron: "0 1 * * *"  
  workflow_dispatch:

jobs:
  clean_report:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: git checkout gh-pages
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: gh-pages
      
      - name: Set Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Delete reports older than 10 days
        timeout-minutes: 3
        run: |
          X_DAYS_AGO_TIMESTAMP=$(date -d "1 days ago" +%s)
          cd reports/
          files=$(git ls-files | xargs -n 1 dirname | uniq)
          
          for folder in $files; do
            echo -n "."
            LAST_MODIFIED_TIMESTAMP=$(git log -1 --format="%at" -- "$folder")
            
            if [ "$LAST_MODIFIED_TIMESTAMP" -lt "$X_DAYS_AGO_TIMESTAMP" ]; then
              echo -e "\nRemoving $file last modified at $(date -d "@$LAST_MODIFIED_TIMESTAMP")"
              git rm -r --quiet "$folder"
            fi
          done

      - name: Push the deleted reports
        timeout-minutes: 2
        run: |
          if ! git diff --exit-code --quiet --staged; then
            git commit -m "Remove files not modified within the last 10 days"
            git push
          else
            echo "No files removed"
          fi

