name: Scheduled Playwright report cleanup 
on:
  schedule:
    - cron: "0 1 * * *"  
  workflow_dispatch:
  push:
    branches: [ gh-pages ]
jobs:
  clean_report:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: git checkout gh-pages
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: gh-pages
      
      - name: Set Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: LS
        run: ls -R -l

      - name: Delete reports older than 10 days
        timeout-minutes: 3
        run: |
          X_DAYS_AGO_TIMESTAMP=$(date -d "$1 days ago" +%s)
          cd reports/
          files=$(git ls-files | xargs -n 1 dirname | uniq)
          echo "Hello 1 $X_DAYS_AGO_TIMESTAMP"
          for folder in $files; do
            echo -n "Hello 2 "
            LAST_MODIFIED_TIMESTAMP=$(git log -1 --format="%at" -- "$folder")
            echo "Hello 3 $folder - $LAST_MODIFIED_TIMESTAMP"
            # If the file hasn't been modified within the last $1 days
            if [ "$LAST_MODIFIED_TIMESTAMP" -lt "$X_DAYS_AGO_TIMESTAMP" ]; then
              # Remove the file from the repository
              echo -e "\nRemoving $file last modified at $(date -d "@$LAST_MODIFIED_TIMESTAMP")"
              echo -n "Hello 4 "
              git rm -r --quiet "$folder"
              echo -n "Hello 5 "
            fi
          done

          if ! git diff --exit-code --quiet --staged; then
            echo -n "Hello 6 "
            git commit -m "Remove files not modified within the last $1 days"
            git push
          else
            echo "No files removed"
          fi
      
      - name: LS
        run: ls -R -l



#subfolders=$(git ls-files | xargs -n 1 dirname | uniq)
#for folder in $subfolders; do
#  echo -n "."
#  LAST_MODIFIED_TIMESTAMP=$(git log -1 --format="%at" -- "$folder")
#  echo -e "\nRemoving $file last modified at $(date -d "@$LAST_MODIFIED_TIMESTAMP")"
#done  