name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout repo
        uses: actions/checkout@v3

      - name: cd playwright 1
        run: ls

      - name: Pull Docker image
        run: docker pull harindu91/playwright-docker:1.0.6

      - name: Run Docker container
        run: docker run --rm 
          -v "${GITHUB_WORKSPACE}/playwright/tests:/app/tests" \ 
          -v "${GITHUB_WORKSPACE}/playwright/tests/playwright.config.js:/app" \
          harindu91/playwright-docker:1.0.6
