name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout repo
        uses: actions/checkout@v3

      - name: Run Node app
        run: |
          cd node-app/
          npm install
          node server.js &

      - name: Pull Docker image
        run: docker pull harindu91/playwright-docker:1.1.2

      - name: Run Tests on Docker container
        run: docker run --rm -v "${GITHUB_WORKSPACE}/playwright/tests:/app/tests" -v "${GITHUB_WORKSPACE}/playwright/playwright-report:/app/playwright-report" -v "${GITHUB_WORKSPACE}/playwright/playwright.config.js:/app/playwright.config.js" -v "${GITHUB_WORKSPACE}/playwright/allure-results:/app/allure-results" -v "${GITHUB_WORKSPACE}/playwright/allure-report:/app/allure-report" harindu91/playwright-docker:1.1.2

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: playwright/allure-results/
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
      
      - name: Output Report URL as Worfklow Annotation
        if: always()
        run: |
          FULL_HTML_REPORT_URL=https://harindu61.github.io/playwright_docker/${{ github.run_number }}
  
          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
    
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
