name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout Cypress Tests
        uses: actions/checkout@v3

      - name: Pull Docker image
        run: docker pull harindu91/playwright-docker:1.0.6

      - name: ls
        run: ls

      - name: Run Docker container
        run: docker run --rm -v "${GITHUB_WORKSPACE}/playwright:/app" harindu91/playwright-docker:1.0.6
