name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: docker pull harindu91/playwright-docker:1.0.1

      - name: Run Docker container
        run: docker run -it --rm  harindu91/playwright-docker:1.0.1
